name: CI

on:
  push:

jobs:
  lint:
    name: Lint, Format, & Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pipenv install
      - run: pipenv shell
      - name: Lint check
        run: pylint .
      - name: Format check
        run: black . --diff
      # - name: mypy
      #   run: mypy .
  
  # test:
  #   runs-on: ubuntu-latest
