name: CI

on:
  push:

jobs:
  lint:
    name: Lint, Format, & Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip3 install pipenv
      - run: pipenv install
      - name: Lint check
        run: pipenv run pylint .
      - name: Format check
        run: pipenv run black . --diff
      # - name: mypy
      #   run: pipenv run mypy .
  
  # test:
  #   runs-on: ubuntu-latest
